
dist: trusty

addons:
  apt:
    packages:
        - texlive-full
before_script:
    - pdflatex -interaction=nonstopmode -halt-on-error main.tex
script:
    - pdflatex -interaction=nonstopmode -halt-on-error  main.tex
before_deploy:
  - mkdir dist
  - cp main.pdf dist
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: false
  on:
    branch: master
