
dist: trusty

addons:
  apt:
    packages:
        - texlive
before_script:
    - pdflatex -interaction=nonstopmode -halt-on-error main.tex
script:
    - pdflatex -interaction=nonstopmode -halt-on-error  main.tex
